#!/usr/bin/env python3
"""Regenerates src/data/shared/shopPrices.js from the official SwimSpa.cz product pages.

The e-shop sells exactly one equipment level per model (Atlas / Aqua Life: Hydro, Atlantis:
Pro Premium, Easy Life: "Pro"), so only that level gets a price; the other levels shown on
the site stay "Na dotaz". Easy Life "Pro" is the 10-speed inverter version (the shop text
says so), i.e. our "Pro Premium". Run again to refresh the prices:  python3 scripts/fetch-shop-prices.py
"""
import html, json, re, time, urllib.request

BASE = 'https://www.swimspa.cz/swim-spa/'
MODELS = {  # our slug -> shop slug
    'atlas-4-4': 'riptide-atlas-hydro-4-4', 'atlas-6-0': 'riptide-atlas-hydro-6-0',
    'aqua-life-4-0': 'riptide-aqua-life-hydro-4-0', 'aqua-life-4-4': 'riptide-aqua-life-hydro-4-4',
    'aqua-life-5-5': 'riptide-aqua-life-hydro-5-5', 'aqua-life-6-0': 'riptide-aqua-life-hydro-6-0',
    'aqua-life-6-0-duo': 'riptide-aqua-life-hydro-6-0-duo',
    'atlantis-4-4': 'riptide-atlantis-pro-premium-4-4', 'atlantis-6-0': 'riptide-atlantis-pro-premium-6-0',
    'atlantis-7-0': 'riptide-atlantis-pro-premium-7-0',
    'easy-life-4-4': 'riptide-easy-life-pro-4-4', 'easy-life-5-5': 'riptide-easy-life-pro-5-5',
    'easy-life-6-0': 'riptide-easy-life-pro-6-0', 'easy-life-6-0-duo': 'riptide-easy-life-pro-6-0-duo',
    'easy-life-7-0': 'riptide-easy-life-pro-7-0', 'easy-life-7-0-duo': 'riptide-easy-life-pro-7-0-duo',
    'easy-life-8-0': 'riptide-easy-life-pro-8-0', 'easy-life-8-0-duo': 'riptide-easy-life-pro-8-0-duo',
}


def tier_of(shop_slug):
    if 'hydro' in shop_slug:
        return 'Hydro'
    if 'pro-premium' in shop_slug or '-easy-life-pro-' in shop_slug:
        return 'Pro Premium'
    raise SystemExit('unknown tier for ' + shop_slug)


prices = {}
for slug, shop in MODELS.items():
    url = BASE + shop + '/'
    page = urllib.request.urlopen(urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'}), timeout=60).read().decode('utf8')
    m = re.search(r'itemprop="price" content="([\d.]+)"', page)
    name = html.unescape(re.sub(r'<[^>]+>', '', re.search(r'<h1[^>]*>(.*?)</h1>', page, re.S).group(1))).strip()
    prices[slug] = {'price': int(float(m.group(1))), 'tier': tier_of(shop), 'shopName': name, 'url': url}
    print(slug, prices[slug]['price'], prices[slug]['tier'])
    time.sleep(0.3)

out = ('// GENERATED by scripts/fetch-shop-prices.py from the official SwimSpa.cz product pages.\n'
       '// One price per model — for the equipment level the e-shop sells (see the script header).\n'
       'export const shopPrices = %s\n' % json.dumps(prices, ensure_ascii=False, indent=2))
open('src/data/shared/shopPrices.js', 'w').write(out)
