#!/usr/bin/env python3
"""Pulls the massage-zone cards and the lighting photo from the official SwimSpa.cz product pages.

The "Detailní popis produktu" block is the same template on all 18 shop pages (verified by
comparing the HTML), so one page is enough. Wording is copied verbatim; the photos are
re-encoded to WebP. Writes src/data/shared/shopDetail.js and public/assets/photos/shop-*.webp.
Needs Pillow:  python scripts/fetch-shop-detail.py
"""
import html, io, json, re, urllib.parse, urllib.request
from PIL import Image

PAGE = 'https://www.swimspa.cz/swim-spa/riptide-aqua-life-hydro-5-5/'
MASSAGE_TITLES = ['Masážní lehátko pro celé tělo', 'Akupresurní masáž zad', 'Masážní stěna']
LIGHTING_TITLE = 'Dream Time Lighting'


def get(url):
    q = urllib.parse.quote(url, safe=':/%')
    return urllib.request.urlopen(urllib.request.Request(q, headers={'User-Agent': 'Mozilla/5.0'}), timeout=60).read()


def clean(s):
    return re.sub(r'\s+', ' ', html.unescape(re.sub(r'<[^>]+>', ' ', s))).strip()


def block(page, title):
    """Text paragraph and first image that follow a heading with this exact title."""
    m = re.search(r'<h[23][^>]*>(?:(?!</h[23]>).)*?' + re.escape(title) + r'.*?</h[23]>(.*?)(?=<h[23]|$)', page, re.S)
    assert m, title
    body = m.group(1)
    text = clean(re.search(r'<p[^>]*>(.*?)</p>', body, re.S).group(1))
    img = re.search(r"<img[^>]+src=['\"]([^'\"]+)['\"]", body).group(1)
    return text, img


def webp(url, name, width=1000):
    im = Image.open(io.BytesIO(get(url))).convert('RGB')
    if im.width > width:
        im = im.resize((width, round(im.height * width / im.width)), Image.LANCZOS)
    im.save('public/assets/photos/%s.webp' % name, 'WEBP', quality=82, method=6)
    return {'src': '/assets/photos/%s.webp' % name, 'width': im.width, 'height': im.height}


page = get(PAGE).decode('utf8')
cards = []
for i, title in enumerate(MASSAGE_TITLES, 1):
    text, img = block(page, title)
    cards.append({'title': title, 'text': text, 'image': webp(img, 'shop-massage-%d' % i)})
ltext, limg = block(page, LIGHTING_TITLE)
lighting = {'title': LIGHTING_TITLE, 'text': ltext, 'image': webp(limg, 'shop-lighting')}

out = ('// GENERATED by scripts/fetch-shop-detail.py from the official SwimSpa.cz product pages\n'
       '// (identical "Detailní popis produktu" block on every model page). Wording is verbatim.\n'
       'export const shopDetail = %s\n' % json.dumps({'source': PAGE, 'massage': cards, 'lighting': lighting},
                                                      ensure_ascii=False, indent=2))
open('src/data/shared/shopDetail.js', 'w').write(out)
print(out)
