#!/usr/bin/env python3
"""Regenerates src/data/shared/reviews.js from the public store ratings on SwimSpa.cz.

Texts are copied verbatim (including the customers' own spelling). Only ratings that carry a
text and don't talk about another brand's product are used; the summary (average, count) is
the shop's own. Run:  python3 scripts/fetch-shop-reviews.py
"""
import html, json, re, urllib.request

URL = 'https://www.swimspa.cz/hodnoceni-obchodu/'
OTHER_BRANDS = re.compile(r'Activity|Passion|Bliss', re.I)  # reviews of products we do not sell here
LIMIT = 6

page = urllib.request.urlopen(urllib.request.Request(URL, headers={'User-Agent': 'Mozilla/5.0'}), timeout=60).read().decode('utf8')
clean = lambda x: html.unescape(re.sub(r'\s+', ' ', re.sub(r'<[^>]+>', ' ', x))).strip()

summary = re.search(r'Průměrné hodnocení obchodu je ([\d,]+) z 5 hvězdiček\. (\d+) hodnocení', clean(page))
items = []
for block in page.split('class="vote-wrap"')[1:]:
    name = re.search(r'data-testid="textRatingAuthor">(.*?)</span>\s*</span>', block, re.S)
    text = re.search(r'class="vote-content"[^>]*>(.*?)</div>', block, re.S)
    date = re.search(r'class="vote-time[^"]*"[^>]*>(.*?)</', block, re.S)
    stars = len(re.findall(r'star star-on', block))
    t = clean(text.group(1)) if text else ''
    if not (name and t) or stars != 5 or OTHER_BRANDS.search(t):
        continue
    items.append({'name': clean(name.group(1)), 'stars': stars, 'date': clean(date.group(1)) if date else '', 'text': t})
items = items[:LIMIT]
assert summary and items, 'page structure changed'

data = {'source': URL, 'average': summary.group(1), 'count': int(summary.group(2)), 'items': items}
open('src/data/shared/reviews.js', 'w').write(
    '// GENERATED by scripts/fetch-shop-reviews.py from the public store ratings on SwimSpa.cz.\n'
    '// Wording is verbatim (customers\' own spelling).\n'
    'export const reviews = %s\n' % json.dumps(data, ensure_ascii=False, indent=2))
print(data['average'], data['count'], [i['name'] for i in items])
