"""Responsive WebP variants + tiny blurred placeholder (LQIP) for every hero photo.

Writes public/assets/photos/<name>-{640,960,1440}.webp (never upscaled) and
src/data/shared/heroImages.js (width list + base64 placeholder per photo).
Run with a Python that has Pillow:  python scripts/gen-hero-images.py
"""
import base64, io, os
from PIL import Image

PHOTOS = 'public/assets/photos'
NAMES = [
    'hero-aerial-swimmer', 'action-swimmer-underwater', 'detail-water-step',
    'lifestyle-collage-family', 'lifestyle-poolside-friends', 'lifestyle-winter-spa',
    'product-duo-terrace',
]
WIDTHS = [640, 960, 1440]

out = {}
for name in NAMES:
    im = Image.open(f'{PHOTOS}/{name}.jpg').convert('RGB')
    w, h = im.size
    widths = []
    for tw in WIDTHS:
        tw = min(tw, w)
        if tw in widths:
            continue
        widths.append(tw)
        im.resize((tw, round(h * tw / w)), Image.LANCZOS).save(
            f'{PHOTOS}/{name}-{tw}.webp', 'WEBP', quality=80, method=6)
    tiny = im.resize((24, max(1, round(24 * h / w))), Image.LANCZOS)
    buf = io.BytesIO()
    tiny.save(buf, 'WEBP', quality=45, method=6)
    out[name] = dict(widths=widths, w=w, h=h, lqip='data:image/webp;base64,' + base64.b64encode(buf.getvalue()).decode())
    print(name, widths, len(out[name]['lqip']), 'chars')

lines = ['// Generated by scripts/gen-hero-images.py — do not edit by hand.', 'export const heroImages = {']
for name, d in out.items():
    lines.append(f"  '{name}': {{ widths: {d['widths']}, w: {d['w']}, h: {d['h']}, lqip: '{d['lqip']}' }},")
lines.append('}')
open('src/data/shared/heroImages.js', 'w').write('\n'.join(lines) + '\n')
